name: Deploy to Firebase Hosting on merge
on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm install
              working-directory: Quamin # Specify the directory containing package.json
            - run: npm run build
              working-directory: Quamin # Specify the directory containing package.json
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_QUAMIN_WEBSITE_DEV }}
                  channelId: live
                  projectId: quamin-website-dev
